### ISSUE TITLE
Incompatible Response Format from qdrant-js Client in LangChain Wrapper

### ISSUE THREAD

**Issue by amrohendawi** [qdrant/openapi-typescript-fetch#4]
**Description:**
The current response format from the `qdrant-js` client contradicts the expected structure in the LangChain.js Qdrant wrapper. This inconsistency disrupts the retrieval of essential data.

**Expected Format:**
LangChain.js Qdrant wrapper anticipates responses to be structured like:

```json
{
  "metadata": {
    "source": "source_info",
    "title": "title_info"
  },
  "pageContent": "content_here"
}
```

**Actual Format:**
However, the `qdrant-js` client provides responses like:

```json
{
  "metadata": {
    "source": "source_info",
    "title": "title_info"
  },
  "page_content": "content_here"
}
```

The distinction lies in the naming of the `pageContent` property, creating a conflict when processed by the LangChain wrapper. Consequently, the wrapper returns undefined `pageContent`.

**Impact and Solution:**
The LangChain wrapper for QdrantVectorStore interprets `page_content` instead of `pageContent`, leading to undefined results. To address this, align the response format with the expected LangChain structure:

```json
{
  "metadata": {
    "source": "source_info",
    "title": "title_info"
  },
  "pageContent": "content_here"
}
```

This modification guarantees compatibility and ensures LangChain.js users receive consistent and accurate data when they use QdrantVectorStore wrapper from [langchain.js](https://github.com/hwchase17/langchainjs).

**Steps to reproduce:**
1. Create QdrantVectorStore instance from langChain.js for a search operation.
Example code snippet:

```javascript
const embeddings = new OpenAIEmbeddings({ openAIApiKey: process.env.OPENAI_API_KEY })

const vectorStore = await QdrantVectorStore.fromExistingCollection(
  embeddings,
  {
    url: process.env.QDRANT_URL,
    collectionName: process.env.QDRANT_COLLECTION_NAME
  })

const results = await vectorStore.similaritySearch("some query", 4)
```

2. In the results notice the `pageContent` property remains undefined due to format inconsistency.

**Expected Outcome:**
Aligning the response format will allow seamless integration, ensuring LangChain.js retrieves the `pageContent` property accurately.

**Note:**
This discrepancy also affects LangChain's GitHub repository for comprehensive resolution.

An issue on langchain.js github repositry under [#2408](https://github.com/hwchase17/langchainjs/issues/2408) has been opened.

**Comment by abdulmansour** [comment]
This is very annoying, agree we should have this addressed.

**Comment by 1951FDG** [comment]
Very annoying

**Comment by Anush008** [comment]
This was resolved in https://github.com/langchain-ai/langchainjs/pull/5172.
